# ConfigMap to Store Database Details
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  labels:
    app: postgres
data:
  POSTGRES_DB: keycloak
  POSTGRES_USER: kcadmin
  POSTGRES_PASSWORD: kcadmin
---
# Persistent Volume to Store Database Details
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume-5g
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql
---
# Persistent Volume Claim to Store Database Details
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim-5g
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
# Postgres Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16.2
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-volume-claim-5g
      volumes:
        - name: postgres-volume-claim-5g
          persistentVolumeClaim:
            claimName: postgres-volume-claim-5g
---
# Postgres Service
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: LoadBalancer
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
